### ISSUE TITLE
How can I install this plugin?

### ISSUE THREAD

**Issue by helix55** [terence-bonhomme/rnhp#25]
I can't find this plugin in the Settings of Remnote, I want to ask how to install this plugin?

**Comment by terence-bonhomme** [comment]
Hello

For the same reasons as rnyt, the plugin can't be installed this way anymore. I haven't updated the documentation yet. 

Only people who installed it before RemNote 1.8 can "use" it, but it is broken. The accounts with old plugins are stuck with them.

The plugin has two issues: broken code and plugin marketplace. I prefer fixing the broken code first, which is not a trivial issue. I should build a basic plugin without levels. It could be better to have something before the complex plugin.

I was busy, but I will have more time to work on it.
